### PR TITLE
Chapter 14: Following Users

### PR DESCRIPTION
**Pull request by hazwanizafirah**

### CODE REVIEW

**Comment by hazwanizafirah** [comment]
ready

**Comment by hazwanizafirah** [comment]
image
I got this error when I click home. Can I know how to fix this?

**Review by ghost — COMMENTED** [review]
It said you have an error in the relationship model. Please check it again

**Comment by hazwanizafirah** [comment]
ready

**Review by huongnt-2545 — APPROVED** [review]
merged
You can merge this pull

**Pull request merged**
